sudo: required
dist: trusty
services: docker
script:
- chmod +x dropbox_uploader.sh
- echo "Everything all right until now"
- "./dropbox_uploader.sh unlink"
- "./dropbox_uploader.sh upload README.md README.md"
before_deploy:
- git config --local user.name "Fmrhj"
- git config --local user.email "ferna.zepeda@gmail.com"
- export LATEST_TAG=$(git describe --tags)
- echo $LATEST_TAG
- chmod +x genTag.sh
- export TRAVIS_TAG=$(./genTag.sh ${LATEST_TAG})
- git tag $TRAVIS_TAG
- echo $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: To2WCd7DcJIRjxibz/n3qRjZ8e0J6xjRz1KjJUZVq2XO6xLTclxJlOY1PEkzB8UKKfNyp36DPF+3tKOcHNJebd8qhR2d6H7IvAwerJtjHlu5eRwE2ua8EAheCQ4YIVOPcxI8WmwcmIVGPQTudREx2wbKHCZ9tDF0fJCpWtRZ3S+3slkqmYNX8p/UWUqNHAbrV8LGRhMmEoiBs6xS0bpER0BCh5LKA35i5UuxKBnPk7BDGvNSw0uLip/FaE+BCfkU5gtCSAxqnhpeIgIAcXUo/ZGhv8vnxwZqdMwBrVSkvBYm3T8fxfd8FOFZCr2Pwrg4foTvKOPv5iOPd/t3kILgh/SISF8exGhL/aBIAsD61oNdoKMetBtQ0+FiReyXyb3VPZIYugdkxp7DWG5ip9OcOLFTm7keS2VCvVMAANZFPd2tkjh1WE9JpiV1rl/aCeUigaFgfh4KbEQMcAtNxQCF4pV9peRsoi8p+MBirzActkBAzONhJBN2No1cJ1wr1em2nbrN0/UwmObWZcZ8zXU1hWXUQK0WRaUcIzMXJacnLJscxe+e46IfuXCj15czkyONuW6fPxPmiCGXt/+HoxqOTExUB2keFCiiPFgIp0h3axuXWfAKB0GP/pAd90HuPEbP1Ym/aol+4niEmuTpuxPbgnvBYY1jLWKbWE11nyEfwWE=
  file: "./_build/main.pdf"
  on:
    repo: Fmrhj/cv-pipeline
    tag: true
before_install:
- openssl aes-256-cbc -K $encrypted_fa1d1a8220a2_key -iv $encrypted_fa1d1a8220a2_iv
  -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
